media: public
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ title, publishedAt, date ]
    fields:
      - name: publishedAt
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text