media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ title, publishedAt ]
    fields:
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: text
      - name: image
        label: Image
        type: image
      - name: author
        label: Author
        type: string
        default: Roy Lo
      - name: publishedAt
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text
  - name: projects
    label: Projects
    type: collection
    path: 'content/projects'
    view:
      fields: [ title, publishedAt ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: summary
        label: Summary
        type: text
      - name: author
        label: Author
        type: string
      - name: image
        label: Cover Image
        type: image
      - name: publishedAt
        label: Date
        type: date
      - name: duration
        label: Duration
        type: string
        required: true
        list:
          collapsible: true
          max: 2
      - name: techStack
        label: Tech Stacks
        type: string
        list: true
      - name: skill
        label: PM Skills
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text
  - name: fragments
    label: Fragments
    type: collection
    path: 'content/fragments'
    view:
      fields: [ title, location, image ]
    fields:
      - name: title
        label: Title
        type: string
      - name: location
        label: Location
        type: string
      - name: image
        label: Image
        type: image
      - name: author
        label: Author
        type: string
        default: Roy Lo
      - name: publishedAt
        label: Date
        type: date