media: public
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ title, publishedAt ]
    fields:
      - name: publishedAt
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: projects
    label: Projects
    type: collection
    path: 'content/projects'
    view:
      fields: [ title, publishedAt ]
    fields:
      - name: summary
        label: Summary
        type: text
      - name: publishedAt
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: tags
        label: techStack
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text
    